# docker-compose.yml

version: '3.9'

services:
  backend:
    build: ./server
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build: ./client
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
